### ISSUE TITLE
Panic when running with incorrect jvm opts

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-java-distribution#120]
This config:

```
configType: java
configVersion: 1
jvmOpts: -XX:-PerfDisableSharedMem
```

Produces this panic:

```
panic: yaml: unmarshal errors:
  line 12: cannot unmarshal !!str `-XX:-Pe...` into []string

goroutine 1 [running]:
panic(0x555de0, 0xc8200d9860)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/palantir/go-java-launcher/launchlib.ParseCustomConfig(0xc820093500, 0x156, 0x356, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/launchlib/config.go:57 +0xf8
main.LaunchWithConfig(0x7fffd6e37e2e, 0x1f, 0x7fffd6e37e4e, 0x1c)
        /home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/go-java-launcher/main.go:36 +0x3d6
main.main()
        /home/ubuntu/.go_workspace/src/github.com/palantir/go-java-launcher/go-java-launcher/main.go:56 +0xf6
```

I would expect to instead get a helpful error message here about the correct format for the `jvmOpts` parameter needing to be a string array rather than just a string.

Corrected config is (from memory):

```
configType: java
configVersion: 1
jvmOpts:
 - "-XX:-PerfDisableSharedMem"
```

**Comment by ash211** [comment]
Alternatively I can see a case being made to support the single string syntax in addition to the string array syntax, in the name of usability.

**Comment by uschi2000** [comment]
Andrew, I'm not sure there's an easy fix here other than maybe adding another, more human-friendly error message: https://github.com/palantir/go-java-launcher/pull/8
