### ISSUE TITLE
Ignore non-JAR artifacts during createManifest

### ISSUE THREAD

**Issue by Dgleish** [palantir/gradle-java-distribution#378]
## What happened?

If I have a product A which has a dependency B with POM packaging (the pom file is the artifact), then I get a stacktrace during the `createManifest` task for product A because it seems to treat the .pom file as a jar and tries to unpack it.
## What did you want to happen?
I think only jars need to be examined to get versions from, so we could just ignore anything that isn't a jar.

**Comment by robert3005** [comment]
```
IOException encountered when processing artifact 'org.apache.spark:spark-dist_2.11-hadoop-palantir:3.0.0-palantir.9', file '/Users/robertk/.gradle/caches/modules-2/files-2.1/org.apache.spark/spark-dist_2.11-hadoop-palantir/3.0.0-palantir.9/305a6ee31d07b227fb040e3c189df408bb67fa6b/spark-dist_2.11-hadoop-palantir-3.0.0-palantir.9.pom'
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at com.palantir.gradle.dist.tasks.CreateManifestTask$_createManifest_closure1.doCall(CreateManifestTask.groovy:109)
        at com.palantir.gradle.dist.tasks.CreateManifestTask$_createManifest_closure1.call(CreateManifestTask.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
```

**Comment by iamdanfox** [comment]
fixed by https://github.com/palantir/sls-packaging/pull/415
